version: 2
jobs:
  test:
    machine: true
    steps:
      - run: echo 'export PATH="$GOPATH/bin:$PATH"' >> $BASH_ENV
      - run: echo 'export GOPATH="$HOME/.go_project"' >> $BASH_ENV
      - run: sudo rm -rf /usr/local/go
      - run: wget https://storage.googleapis.com/golang/go1.13.linux-amd64.tar.gz
      - run: sudo tar -C /usr/local -xzf go1.13.linux-amd64.tar.gz
      - run: mkdir -p ~/.go_project/src/github.com/TimeIncOSS
      - run: go get github.com/TimeIncOSS/ape-dev-rt
      - run: ln -s $(pwd) ~/.go_project/src/github.com/TimeIncOSS/ape-dev-rt
      - run: wget https://releases.hashicorp.com/terraform/0.11.0/terraform_0.11.0_linux_386.zip
      - run: sudo unzip terraform_0.11.0_linux_386.zip -d /usr/local/bin
      - run:
          name: install deps
          command: |
             cd ../.go_project/src/github.com/TimeIncOSS/ape-dev-rt
             make installdeps
      - run:
          name: run test
          command: |
             cd ../.go_project/src/github.com/TimeIncOSS/ape-dev-rt
             make test
workflows:
  version: 2
  deployment-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
