version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13.5
    working_directory: /go/src/github.com/MeredithCorpOSS/ape-dev-rt
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_386.zip
      - run: sudo unzip terraform_0.12.29_linux_386.zip -d /usr/local/bin
      - run:
          name: install deps
          command: |
             make installdeps
      - run:
          name: run test
          command: |
             make test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
